build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'
